#!/usr/bin/env bash

set -e

WBROWSER='/usr/bin/chromium'
DATABASE="${HOME}/.local/share/browser_bookmarks/bookmarks.json"

CATEGORY=$(
  jq -r '. | keys' <"$DATABASE" |
    sed -n '/^[^][]/p' |
    sed 's/[][", ]//g' |
    rofi -dmenu
)

[ -n "$CATEGORY" ] || exit 101

BOOKMARK=$(
  jq -r '.'"$CATEGORY"' | keys[] as $k | "\($k): \(.[$k].dsc)"' <"$DATABASE" |
    sed -n '/^[^][]/p' |
    sed 's/[][", ]//g' |
    rofi -dmenu |
    cut -d':' -f1
)

[ -n "$BOOKMARK" ] || exit 102

ADDRESS=$(
  jq -r '.'"$CATEGORY"'["'"$BOOKMARK"'"]["url"]' <"$DATABASE" | sed 's/"//g'
)

[ -n "$ADDRESS" ] || exit 103

"$WBROWSER" "$ADDRESS" &

exit 0
