#!/usr/bin/env bash

set -e

WBROWSER='/usr/bin/chromium'
DATABASE="${HOME}/downloads/bookmarks.json"

CATEGORY=$(
  jq '. | keys' <"$DATABASE" |
    sed -n '/^[^][]/p' |
    sed 's/[][", ]//g' |
    rofi -dmenu
)

[ -n "$CATEGORY" ] || exit 101

BOOKMARK=$(
  JQ=".$CATEGORY | keys[] as \$k | \"\(\$k): \(.[\$k].dsc)\""
  jq -r "$JQ" <"$DATABASE" |
    sed -n '/^[^][]/p' |
    sed 's/[][", ]//g' |
    rofi -dmenu | cut -d':' -f1
)

ADDRESS=$(
  JQ=$(printf '.%s["%s"]["url"]' "$CATEGORY" "$BOOKMARK")
  jq "$JQ" <"$DATABASE" | sed 's/"//g'
)

[ -n "$ADDRESS" ] || exit 102

"$WBROWSER" "$ADDRESS" &

exit 0
