#!/usr/bin/env bash

set -e

WBROWSER='/usr/bin/chromium'
DATABASE="${HOME}/.local/share/browser_bookmarks/bookmarks.json"

CATEGORY=$(
  jq -r '. | keys' <"$DATABASE" |
    sed -n '/^[^][]/p' |
    sed 's/[][", ]//g' |
    rofi -dmenu
)

[ -n "$CATEGORY" ] || exit 101

BOOKMARK=$(
  jq -r '.'"$CATEGORY"' | keys[] as $k | "\(.[$k].url)"' <"$DATABASE" |
    sed -n '/^[^][]/p' |
    sed 's/[][", ]//g' |
    rofi -dmenu
)

[ -n "$BOOKMARK" ] || exit 102

"$WBROWSER" "$BOOKMARK" &

exit 0
