#!/usr/bin/env bash
################################################################################
# Author:                                                                      #
#                                                                              #
#   Marcelo Barboza <salve.barboza@pm.me>                                      #
#                                                                              #
# Dependencies:                                                                #
#                                                                              #
#   - Ag/Telescope                                                             #
#   - bash                                                                     #
#   - find                                                                     #
#   - fzf                                                                      #
#   - jq                                                                       #
#   - vim/nvim                                                                 #
#   - sed                                                                      #
#   - sort                                                                     #
#   - tail                                                                     #
#   - tr                                                                       #
#                                                                              #
# Purpose:                                                                     #
#                                                                              #
#   - Create/Edit notes in LaTeX with Vim/Neovim                               #
#                                                                              #
# Last changed:                                                                #
#                                                                              #
#   Goiânia, 07 de fevereiro de 2025                                           #
#                                                                              #
################################################################################
################################################################################
# TODO:                                                                        #
#   - Make `cnote -e` utilize the metadata file and open the apropriate note   #
#     in vim                                                                   #
################################################################################

ROOT="${HOME}/projects/notes"
JSON="${ROOT}/tex/index.json"
LTEX="${ROOT}/tex/index.tex"

[[ $# -eq 1 ]] || exit 10
[[ -d "$ROOT" ]] || exit 11
[[ -f "$JSON" ]] || exit 12

# TGTDIR {{{
function TGTDIR() {
  CRSE=$(jq -r 'keys[] as $k | "\($k): \(.[$k].code), \(.[$k].discipline), T\(.[$k].class), \(.[$k].workload)"' <"$JSON" | fzf)
  CODE=$(echo "$CRSE" | cut -d ':' -f 1)
  DEST="${ROOT}/tex/${CODE}"
}
# }}}

# CREATE {{{
function CREATE() {
  [[ -d "$DEST" ]] || mkdir -p "$DEST"
  if find "$DEST" -type f -name '*.tex'; then
    M=$(find "$DEST" -type f -name '*.tex' | sort | tail -1 | sed "s@${DEST}/\([0-9]\{3\}\)\.tex@\1@g" | sed 's/\<0\+//')
  else
    M=0
  fi
  N=$(printf '%03d' "$((M + 1))")
  TGT_JSON_FILE="${DEST}/${N}.json"
  TGT_TEX_FILE="${DEST}/${N}.tex"
  vim -O "$TGT_JSON_FILE" "$TGT_TEX_FILE"
  # nvim -O "$TGT_JSON_FILE" "$TGT_TEX_FILE"
  find "$DEST" -type f -name '*.tex' | sort | tail -2 | sed "s@${DEST}/\([0-9]\{3\}\)\.tex@\\\\input{tex/${CODE}/\1}@" >"$LTEX"
}
# }}}

# EDIT {{{
function EDIT() {
  [[ -d "$DEST" ]] || exit 13
  [[ -n "$(find "$DEST" -type f -name '*.tex')" ]] || exit 14
  cd "$DEST" || exit 15
  vim -c 'Ag'
  # nvim -c 'Telescope find_files'
}
# }}}

# HELP {{{
function HELP() {
  printf '
  Usage: cnote [OPTION]

  \tShell script that helps me quickly and correctly place my math notes writen
  \tin LaTeX.

  Available options:

  [-c|--create]

  \tCreates notes sequentially. First, it prompts the user for the directory in
  \twhich to save the notes. Then, inside the chosen directory, it creates both
  \ta notes file (TeX) and a metadata (json) file.

  [-e|--edit]

  \tAsks the user for the directory in which to find the notes file to be
  \tedited. Then, it prompts the user with a live grep environment so that
  \the/she can find the notes file to be edited based on strings from within
  \tthat file.

  [-m|--make]

  \tCompiles a draft version of the document.

  [-h|--help]

  Error codes:

  \t10: wrong number of arguments
  \t11: notes directory does not exist
  \t12: index file (json) does not exist
  \t13: target dir does not exist
  \t14: there are no files to edit
  \t15: could not cd into the target destination
  \t16: cound not cd into thr root directory in order to compile document\n\n'
}
# }}}

# CASE STATEMENT {{{
case "$1" in
-c | --create)
  TGTDIR
  CREATE
  ;;
-e | --edit)
  TGTDIR
  EDIT
  ;;
-m | --make)
  cd "$ROOT" || exit 16
  make draft
  ;;
-h | --help)
  HELP
  ;;
*)
  HELP
  ;;
esac
# }}}

exit 0
