#!/usr/bin/env bash
################################################################################
# Author:                                                                      #
#                                                                              #
#   Marcelo Barboza <salve.barboza@pm.me>                                      #
#                                                                              #
# Dependencies:                                                                #
#                                                                              #
#   - bash                                                                     #
#   - dd                                                                       #
#   - gpg                                                                      #
#   - grep                                                                     #
#   - sha512sum                                                                #
#   - wget                                                                     #
#                                                                              #
# Purpose:                                                                     #
#                                                                              #
#   - Download amd64-netinst.iso from Debian GNU/Linux                         #
#   - Verify both the authenticity and the integrity of the downloaded iso     #
#   - Create an USB installation media (target device defaults to /dev/sdb)    #
#                                                                              #
# Last changed:                                                                #
#                                                                              #
#   Goiânia, 02 de fevereiro de 2025                                           #
#                                                                              #
################################################################################

URL='https://cdimage.debian.org/debian-cd/current/amd64/iso-cd'
VER='13.0.0'
ISO="debian-${VER}-amd64-netinst.iso"
SUM='SHA512SUMS'
SGN='SHA512SUMS.sign'
DIR="${HOME}/downloads/debian"
TGT='/dev/sdb'

[[ -d "$DIR"         ]]  || mkdir -p "$DIR"                || exit 10
[[ "$(pwd)" = "$DIR" ]]  || cd "$DIR"                      || exit 11
[[ -f "$SUM"         ]]  || wget "${URL}/${SUM}" -O "$SUM" || exit 12
[[ -f "$SGN"         ]]  || wget "${URL}/${SGN}" -O "$SGN" || exit 13
[[ -f "$ISO"         ]]  || wget "${URL}/${ISO}" -O "$ISO" || exit 14

if ! gpg -k | grep -qF 'rsa4096/0x988021A964E6EA7D'; then
  gpg --keyserver keyring.debian.org --recv-keys 988021A964E6EA7D
fi

if ! gpg -k | grep -qF 'rsa4096/0xDA87E80D6294BE9B'; then
  gpg --keyserver keyring.debian.org --recv-keys DA87E80D6294BE9B
fi

gpg --verify "$SGN" "$SUM"
sha512sum -c --ignore-missing "$SUM"

echo -n "Do you want to create an installation media for debian $VER amd64?"
echo -n " All data on the target USB device $TGT will be destroyed."
echo -n ' (y/N) '
read -r ANSWER

if [[ "$ANSWER" = 'y' ]]; then
  sudo dd if="$ISO" of="$TGT" bs=16M status=progress oflag=sync
fi

exit 0
