#!/usr/bin/env bash
################################################################################
# Author:                                                                      #
#                                                                              #
#   Marcelo Barboza <salve.barboza@pm.me>                                      #
#                                                                              #
# Dependencies:                                                                #
#                                                                              #
#   - bash                                                                     #
#   - dd                                                                       #
#   - minisign                                                                 #
#   - sha256sum                                                                #
#   - wget                                                                     #
#                                                                              #
# Purpose:                                                                     #
#                                                                              #
#   - Download void-live-x86_64-{version}-xfce.iso from voidlinux.org          #
#   - Verify both the authenticity and the integrity of the downloaded iso     #
#   - Create an USB installation media (target device defaults to /dev/sdb)    #
#                                                                              #
# Last changed:                                                                #
#                                                                              #
#   Goiânia, 30 de dezembro de 2025                                            #
#                                                                              #
################################################################################

URL='https://repo-default.voidlinux.org/live/current'
GHR='https://github.com/void-linux/void-packages/blob/master/srcpkgs/void-release-keys/files'
VRS='20250202'
ISO="void-live-x86_64-${VRS}-xfce.iso"
PGP='sha256sum.sig'
SHA="sha256sum.txt"
PUB="void-release-${VRS}.pub"
DIR="${HOME}/downloads/voidlinux"
TGT='/dev/sdb'

[[ -d "$DIR"         ]] || mkdir -p "$DIR"                       || exit 10
[[ "$(pwd)" = "$DIR" ]] || cd "$DIR"                             || exit 11
[[ -f "$ISO"         ]] || wget "${URL}/$ISO" -O "${DIR}/${ISO}" || exit 12
[[ -f "$PGP"         ]] || wget "${URL}/$PGP" -O "${DIR}/${PGP}" || exit 13
[[ -f "$SHA"         ]] || wget "${URL}/$SHA" -O "${DIR}/${SHA}" || exit 14
[[ -f "$PUB"         ]] || wget "${GHR}/$PUB" -O "${DIR}/${PUB}" || exit 15

printf '\nVerifying the signature:\n\n'
minisign -V -p "$PUB" -x sha256sum.sig -m sha256sum.txt

printf '\nVerifying the integrity:\n\n'
sha256sum -c --ignore-missing sha256sum.txt

echo -n 'Do you want to create an installation media for voidlinux? '
echo -n "All data on the target USB device $TGT will be destroyed. "
echo -n '(y/N) '
read -r ANSWER

if [[ "$ANSWER" = 'y' ]]; then
  sudo dd if="$ISO" of="$TGT" bs=16M status=progress oflag=sync
fi

exit 0
