#!/usr/bin/env bash
###############################################################################
# author: Marcelo Barboza <salve.barboza@pm.me>                               #
# date: 2025-01-22                                                            #
###############################################################################

set -e

# PKGADD {{{
function PKGADD() {
  STATUS="$1"
  BUNDLE="$2"
  if [[ -n "$(dpkg -l | sed -n "/^ii\s\+\<${BUNDLE}\>\s\+/p")" ]]; then
    echo "Found: ${BUNDLE}"
  else
    if [[ "$STATUS" = '--install-all-packages-in-a-new-debian-system' ]]; then
      echo -n "Package ${BUNDLE} not found."
      if echo "$BUNDLE" | grep -qF ':amd64'; then
        STACKS="${BUNDLE/%:amd64/}"
        sudo apt install -y "$STACKS"
      else
        sudo apt install -y "$BUNDLE"
      fi
      echo "Done installing ${BUNDLE}."
    else
      echo -n "Package ${BUNDLE} not found."
      echo -n " Would you like to install it? (y/N) "
      read -r ANSWER
      if [[ "$ANSWER" = 'y' ]]; then
        if echo "$BUNDLE" | grep -qF ':amd64'; then
          STACKS="${BUNDLE/%:amd64/}"
          sudo apt install -y "$STACKS"
        else
          sudo apt install -y "$BUNDLE"
        fi
        echo "Done installing ${BUNDLE}."
      fi
    fi
  fi
}
# }}}

# HELP {{{
function HELP() {
  printf '
  Usage: idebp [OPTION]

  \tInstalls my selection of packages on a Debian GNU/Linux system using apt.

  Available options:

  [-a|--install-all-packages-in-a-new-debian-system]

  \tAs the name suggests, this is intended to be used on a fresh installation of
  \tDebian. By default, it appends the -y flag to every package in the list.

  [-i|--install-missing-packages]

  \tInstall missing packages individually. Does not append the -y flag by
  \tdefault. Should be invoked every time a new package is added to the list.

  [-h|--help]

  \tPrints this message on the screen.\n\n'
}
# }}}

# DEVELOPMENT_IN_C {{{
declare -a DEVELOPMENT_IN_C=(
  build-essential
  gdb
  glibc-doc
  universal-ctags
  valgrind
)
# }}}
# DEVELOPMENT_IN_PYTHON {{{
declare -a DEVELOPMENT_IN_PYTHON=(
  python3-venv
  python3-pip
)
# }}}
# DATABASES {{{
declare -a DATABASES=(
  mariadb-client
  mariadb-server
  postgresql
  postgresql-client
  sqlite3
  sqlite3-doc
)
# }}}
# CONTAINERS {{{
declare -a CONTAINERS=(
  podman
  podman-compose
)
# }}}
# MAIL_CHAT_NEWS_WEB {{{
declare -a MAIL_CHAT_NEWS_WEB=(
  abook
  irssi
  mutt
  newsboat
  w3m
)
# }}}
# FUN_AND_GAMES {{{
declare -a FUN_AND_GAMES=(
  bsdgames
  cowsay
  fastfetch
  figlet
  fortunes
  lolcat
)
# }}}
# SECURITY {{{
declare -a SECURITY=(
  keychain
  pass
  pass-otp
  signify-openbsd
  signify-openbsd-keys
  ufw
)
# }}}
# BLOGGING {{{
declare -a BLOGGING=(
  hugo
  lowdown
)
# }}}
# PDF_DOCUMENT_VIEWERS_AND_UTILS {{{
declare -a PDF_DOCUMENT_VIEWERS_AND_UTILS=(
  qpdf
  zathura
  zathura-djvu:amd64
)
# }}}
# FUZZY_FINDERS {{{
declare -a FUZZY_FINDERS=(
  fd-find
  fzf
  plocate
  ripgrep
  silversearcher-ag
)
# }}}
# FILE_MANAGEMENT {{{
declare -a FILE_MANAGEMENT=(
  vifm
)
# }}}
# MONEY {{{
declare -a MONEY=(
  ledger
)
# }}}
# GIT_WRAPPER_FOR_REMOTE_REPOS {{{
declare -a GIT_WRAPPER_FOR_REMOTE_REPOS=(
  gh
  tea-cli
)
# }}}
# CLI_UTILS {{{
declare -a CLI_UTILS=(
  9base
  jq
  mpv
  redshift
  sc-im
  scrot
  sdcv
  stow
  tmux
  xdotool
)
# }}}
# ZSH {{{
declare -a ZSH=(
  zsh
  zsh-autosuggestions
  zsh-doc
  zsh-syntax-highlighting
)
# }}}
# TERMINAL_CLIENT {{{
declare -a TERMINAL_CLIENT=(
  alacritty
  kitty
)
# }}}
# LATEX {{{
declare -a LATEX=(
  texlive-full
  bibtool
)
# }}}
# IMAGE {{{
declare -a IMAGE=(
  gimp
  inkscape
  xournalpp
)
# }}}
# BROWSER {{{
declare -a BROWSER=(
  chromium
  chromium-driver
)
# }}}
# AWESOME {{{
declare -a AWESOME=(
  awesome
  conky-all
  picom
)
# }}}
# SUCKLESS {{{
declare -a SUCKLESS=(
  libx11-dev:amd64
  libxft-dev:amd64
  libxinerama-dev:amd64
  libharfbuzz-dev:amd64
  libxrandr-dev:amd64
)
# }}}
# NEOVIM {{{
declare -a NEOVIM=(
  ninja-build
  gettext
  cmake
  unzip
  curl
)
# }}}
# VIM {{{
declare -a VIM=(
  vim-nox
  vim-gtk3
)
# }}}
# ANDROID {{{
declare -a ANDROID=(
  adb
  fastboot
)
# }}}

# BUNDLES {{{
BUNDLES=(
  "${DEVELOPMENT_IN_C[@]}"
  "${DEVELOPMENT_IN_PYTHON[@]}"
  "${DATABASES[@]}"
  "${CONTAINERS[@]}"
  "${MAIL_CHAT_NEWS_WEB[@]}"
  "${FUN_AND_GAMES[@]}"
  "${SECURITY[@]}"
  "${BLOGGING[@]}"
  "${PDF_DOCUMENT_VIEWERS_AND_UTILS[@]}"
  "${FUZZY_FINDERS[@]}"
  "${FILE_MANAGEMENT[@]}"
  "${MONEY[@]}"
  "${GIT_WRAPPER_FOR_REMOTE_REPOS[@]}"
  "${CLI_UTILS[@]}"
  "${ZSH[@]}"
  "${TERMINAL_CLIENT[@]}"
  "${LATEX[@]}"
  "${IMAGE[@]}"
  "${BROWSER[@]}"
  "${AWESOME[@]}"
  "${SUCKLESS[@]}"
  "${NEOVIM[@]}"
  "${VIM[@]}"
  "${ANDROID[@]}"
)
# }}}

# INSTALLING BUNDLES {{{
if [[ "$#" -eq 1 ]]; then
  case "$1" in
  -a | --install-all-packages-in-a-new-debian-system)
    for BUNDLE in "${BUNDLES[@]}"; do
      PKGADD --install-all-packages-in-a-new-debian-system "$BUNDLE"
    done
    ;;
  -i | --install-missing-packages)
    for BUNDLE in "${BUNDLES[@]}"; do
      PKGADD --install-missing-packages "$BUNDLE"
    done
    ;;
  *)
    HELP
    ;;
  esac
else
  HELP
fi
# }}}

exit 0
