#!/usr/bin/env bash

FLATPAK_REPO='https://flathub.org/repo/flathub.flatpakrepo'

# BOOTSTRAP {{{
function BOOTSTRAP() {
  if dpkg -l | grep -qE '\<flatpak\>'; then
    echo "The 'flatpak' package is already installed."
  else
    echo "The 'flatpak' package is not installed."
    echo 'Do you want to install it? (y/N)'
    read -r ANSWER
    if [ "${ANSWER}" = 'y' ]; then
      echo 'Proceeding with installation.'
      sudo apt install -y flatpak
      sudo flatpak remote-add --if-not-exists flathub "${FLATPAK_REPO}"
    fi
  fi
}
# }}}

# INSTALL {{{
function install() {
  if flatpak list | grep -qE "\<${FLATPAK}\>"; then
    echo "Found: ${FLATPAK}"
  else
    echo "Flatpak package ${FLATPAK} not found."
    echo 'Would you like to install it? (y/N)'
    read -r ANSWER
    if [ "${ANSWER}" = 'y' ]; then
      echo 'Proceeding with package installation.'
      flatpak install "${FLATPAK}"
      echo 'Done.'
    fi
  fi
}
# }}}

# FLATPAKS {{{
declare -a FLATPAKS=(
  com.spotify.Client
  org.zotero.Zotero
)
# }}}

BOOTSTRAP

for FLATPAK in "${FLATPAKS[@]}"; do
  install "$FLATPAK"
done

exit 0
