#!/usr/bin/env bash

ADDRESS='https://github.com/ryanoasis/nerd-fonts/releases/download'
VERSION='v3.4.0'

FNTDIR="${HOME}/.local/share/fonts"
TMPDIR="${HOME}/downloads/nerdfonts"

[[ -d "${FNTDIR}" ]] || mkdir -p "${FNTDIR}"
[[ -d "${TMPDIR}" ]] || mkdir -p "${TMPDIR}"

# AVAILABLE_FONTS {{{
AVAILABLE_FONTS=$(
  cat <<EOF
0xProto
3270
Agave
AnonymousPro
Arimo
AurulentSansMono
BigBlueTerminal
BitstreamVeraSansMono
CascadiaCode
CascadiaMono
CodeNewRoman
ComicShannsMono
CommitMono
Cousine
D2Coding
DaddyTimeMono
DejaVuSansMono
DepartureMono
DroidSansMono
EnvyCodeR
FantasqueSansMono
FiraCode
FiraMono
GeistMono
Go-Mono
Gohu
Hack
Hasklig
HeavyData
Hermit
iA-Writer
IBMPlexMono
Inconsolata
InconsolataGo
InconsolataLGC
IntelOneMono
Iosevka
IosevkaTerm
IosevkaTermSlab
JetBrainsMono
Lekton
LiberationMono
Lilex
MartianMono
Meslo
Monaspace
Monofur
Monoid
Mononoki
MPlus
NerdFontsSymbolsOnly
Noto
OpenDyslexic
Overpass
ProFont
ProggyClean
Recursive
RobotoMono
ShareTechMono
SourceCodePro
SpaceMono
Terminus
Tinos
Ubuntu
UbuntuMono
UbuntuSans
VictorMono
ZedMono
EOF
)
# }}}

FONTNAME="$(echo "$AVAILABLE_FONTS" | fzf)"

if [[ ! -d "${FNTDIR}/${FONTNAME}" ]]; then
  mkdir -p "${FNTDIR}/${FONTNAME}"
  PKGONLINE="${ADDRESS}/${VERSION}/${FONTNAME}.tar.xz"
  PKGONDISK="${TMPDIR}/${FONTNAME}.tar.xz"
  wget "${PKGONLINE}" -O "${PKGONDISK}"
  xzcat "${PKGONDISK}" | tar xvf - -C "${FNTDIR}/${FONTNAME}"
  rm -rf "${PKGONDISK}"
fi

find "${FNTDIR}" -type f -regextype sed -regex "^.*\(LICENSE\|\.md\|\.txt\)$" -delete

fc-cache -fv

[[ -d "${TMPDIR}" ]] && rm -rf "${TMPDIR}"

exit 0
