#!/usr/bin/env bash

function SOURCE() {
  SRC1='reserved'
  SRC2='dotfiles'

  declare -A ORIG

  ORIG[abook]="$SRC1"
  ORIG[git]="$SRC1"
  ORIG[irssi]="$SRC1"
  ORIG[mutt]="$SRC1"
  ORIG[alacritty]="$SRC2"
  ORIG[containers]="$SRC2"
  ORIG[kanata_cfg]="$SRC2"
  ORIG[kanata_ctl]="$SRC2"
  ORIG[lf]="$SRC2"
  ORIG[nvim]="$SRC2"
  ORIG[tmux]="$SRC2"
  ORIG[vim]="$SRC2"
  ORIG[zathura]="$SRC2"
  ORIG[zsh]="$SRC2"

  PKG="$1"
  echo "${HOME}/projects/${ORIG[$PKG]}/program"
}

function TARGET() {
  declare -A DEST

  DEST[abook]='.abook'
  DEST[git]='.config/git'
  DEST[irssi]='.irssi'
  DEST[mutt]='.mutt'
  DEST[alacritty]='.config/alacritty'
  DEST[containers]='.config/containers'
  DEST[kanata_cfg]='.config/kanata'
  DEST[kanata_ctl]='.config/systemd/user'
  DEST[lf]='.config/lf'
  DEST[nvim]='.config/nvim'
  DEST[tmux]='.config/tmux'
  DEST[vim]='.vim'
  DEST[zathura]='.config/zathura'
  DEST[zsh]='.config/zsh'

  PKG="$1"
  echo "${HOME}/${DEST[$PKG]}"
}

function INSTALL() {
  PKG="$1"
  SRC=$(SOURCE "$PKG")
  TGT=$(TARGET "$PKG")
  [ -d "$TGT" ] && exit 2
  mkdir -p "$TGT"
  stow --restow --dir="$SRC" --target="$TGT" "$PKG"
}

function UNINSTALL() {
  PKG="$1"
  SRC=$(SOURCE "$PKG")
  TGT=$(TARGET "$PKG")
  [ -d "$TGT" ] || exit 3
  stow --delete --dir="$SRC" --target="$TGT" "$PKG"
  rm -rf "$TGT"
}

function AVAILABLE_DOTFILES() {
  printf 'There are dotfiles currently available for the following programs:\n
  \t- abook
  \t- alacritty
  \t- containers
  \t- git
  \t- irssi
  \t- mutt
  \t- kanata
  \t- lf
  \t- nvim
  \t- tmux
  \t- vim
  \t- zathura
  \t- zsh\n\n'
}

function HELP() {
  echo 'Help message'
}

if [ "$#" -eq 2 ]; then
  ACT="$1"
  PKG="$2"
  case "$ACT" in
    -i | --install)
      case "$PKG" in
        abook)
          INSTALL abook
          ;;
        git)
          INSTALL git
          ;;
        irssi)
          INSTALL irssi
          ;;
        mutt)
          INSTALL mutt
          ;;
        alacritty)
          INSTALL alacritty
          ;;
        containers)
          INSTALL containers
          ;;
        kanata)
          INSTALL kanata_cfg
          INSTALL kanata_ctl
          ;;
        lf)
          INSTALL lf
          ;;
        nvim)
          INSTALL nvim
          ;;
        tmux)
          INSTALL tmux
          ;;
        vim)
          INSTALL vim
          ;;
        zathura)
          INSTALL zathura
          ;;
        zsh)
          INSTALL zsh
          ;;
        all)
          INSTALL abook
          INSTALL git
          INSTALL irssi
          INSTALL mutt
          INSTALL alacritty
          INSTALL containers
          INSTALL kanata_cfg
          INSTALL kanata_ctl
          INSTALL lf
          INSTALL nvim
          INSTALL tmux
          INSTALL vim
          INSTALL zathura
          INSTALL zsh
          ;;
        *)
          AVAILABLE_DOTFILES
          ;;
      esac
      ;;
    -u | --uninstall)
      case "$PKG" in
        abook)
          UNINSTALL abook
          ;;
        git)
          UNINSTALL git
          ;;
        irssi)
          UNINSTALL irssi
          ;;
        mutt)
          UNINSTALL mutt
          ;;
        alacritty)
          UNINSTALL alacritty
          ;;
        containers)
          UNINSTALL containers
          ;;
        kanata)
          UNINSTALL kanata_cfg
          UNINSTALL kanata_ctl
          ;;
        lf)
          UNINSTALL lf
          ;;
        nvim)
          UNINSTALL nvim
          ;;
        tmux)
          UNINSTALL tmux
          ;;
        vim)
          UNINSTALL vim
          ;;
        zathura)
          UNINSTALL zathura
          ;;
        zsh)
          UNINSTALL zsh
          ;;
        all)
          UNINSTALL abook
          UNINSTALL git
          UNINSTALL irssi
          UNINSTALL mutt
          UNINSTALL alacritty
          UNINSTALL containers
          UNINSTALL kanata_cfg
          UNINSTALL kanata_ctl
          UNINSTALL lf
          UNINSTALL nvim
          UNINSTALL tmux
          UNINSTALL vim
          UNINSTALL zathura
          UNINSTALL zsh
          ;;
        *)
          AVAILABLE_DOTFILES
          ;;
      esac
      ;;
    *)
      HELP
      ;;
  esac
else
  HELP
fi

exit 0
