#!/usr/bin/env bash
################################################################################
# Author:                                                                      #
#                                                                              #
#   Marcelo Barboza <salve.barboza@pm.me>                                      #
#                                                                              #
# Dependencies:                                                                #
#                                                                              #
#   - bash                                                                     #
#   - dd                                                                       #
#   - gpg                                                                      #
#   - grep                                                                     #
#   - md5sum                                                                   #
#   - wget                                                                     #
#                                                                              #
# Purpose:                                                                     #
#                                                                              #
#   - Download slackware64-15.0-install-dvd.iso from slackware.com             #
#   - Verify both the authenticity and the integrity of the downloaded iso     #
#   - Create an USB installation media (target device defaults to /dev/sdb)    #
#                                                                              #
# Last changed:                                                                #
#                                                                              #
#   Goiânia, 02 de fevereiro de 2025                                           #
#                                                                              #
################################################################################

# vars: AD1, AD2, DIR, ISO, ASC, MD5, TXT, KEY {{{
AD1="https://mirrors.slackware.com/slackware/slackware64-15.0/"
AD2="https://mirrors.slackware.com/slackware/slackware-iso/slackware64-15.0-iso/"
DIR="${HOME}/downloads/slackware"
ISO='slackware64-15.0-install-dvd.iso'
ASC='slackware64-15.0-install-dvd.iso.asc'
MD5='slackware64-15.0-install-dvd.iso.md5'
TXT='slackware64-15.0-install-dvd.iso.txt'
KEY='GPG-KEY'
TGT='/dev/sdb'
# }}}

[[ -d "$DIR"         ]]  || mkdir -p "$DIR"                || exit 10
[[ "$(pwd)" = "$DIR" ]]  || cd "$DIR"                      || exit 11
[[ -f "$KEY"         ]]  || wget "${AD1}/${KEY}" -O "$KEY" || exit 12
[[ -f "$ISO"         ]]  || wget "${AD2}/${ISO}" -O "$ISO" || exit 13
[[ -f "$ASC"         ]]  || wget "${AD2}/${ASC}" -O "$ASC" || exit 14
[[ -f "$MD5"         ]]  || wget "${AD2}/${MD5}" -O "$MD5" || exit 15
[[ -f "$TXT"         ]]  || wget "${AD2}/${TXT}" -O "$TXT" || exit 16

if ! gpg -k | grep -qF 'dsa1024/0x6A4463C040102233'; then
  gpg --import "${KEY}"
fi

gpg --verify "$ASC" "$ISO"
md5sum -c --ignore-missing "$MD5"

echo -n 'Do you want to create an installation media for slackware64 15.0? '
echo -n "All data on the target USB device $TGT will be destroyed. "
echo -n '(y/N) '
read -r ANSWER

if [ "$ANSWER" = 'y' ]; then
  sudo dd if="$ISO" of="$TGT" bs=16M status=progress oflag=sync
fi

exit 0
