#!/usr/bin/env bash
################################################################################
# Author:                                                                      #
#                                                                              #
#   Marcelo Barboza <salve.barboza@pm.me>                                      #
#                                                                              #
# Dependencies:                                                                #
#                                                                              #
#   - Ag/Telescope                                                             #
#   - bash                                                                     #
#   - find                                                                     #
#   - fzf                                                                      #
#   - jq                                                                       #
#   - vim/nvim                                                                 #
#   - sed                                                                      #
#   - sort                                                                     #
#   - tail                                                                     #
#   - tr                                                                       #
#                                                                              #
# Purpose:                                                                     #
#                                                                              #
#   - Create/Edit notes in LaTeX with Vim/Neovim                               #
#                                                                              #
# Last changed:                                                                #
#                                                                              #
#   Goiânia, 07 de fevereiro de 2025                                           #
#                                                                              #
################################################################################

ROOT="${HOME}/projects/zettelkasten"

[ -d "$ROOT" ] || exit 10

# CREATE {{{
function CREATE() {
  UNIQ=$(date +'%Y%m%d%H%M')
  NOTE="${ROOT}/${UNIQ}.md"
  [ -f "$NOTE" ] || vim "$NOTE"
}
# }}}

# SORT_TAGS_ALPHABETICALLY {{{
function SORT_TAGS_ALPHABETICALLY() {
  DATE='[0-9]\{4\}\(0[1-9]\|1[0-2]\)\(0[1-9]\|[12][0-9]\|3[01]\)'
  TIME='\([01][0-9]\|2[0-3]\)\([0-5][0-9]\)'
  NOTE="${ROOT}/${DATE}${TIME}\.md"
  find "$ROOT/" -type f -regextype sed -regex "$NOTE" -exec sed -n '/^tags:$/,/^---$/p' {} \; |
    sed -n '/^\(---\|tags:\)$/!p' | sed 's/^\s\+-\s//' | sort -u
}
# }}}

# SORT_TITLES_CHRONOLOGICALLY {{{
function SORT_TITLES_CHRONOLOGICALLY() {
  grep -E '^title:' "$ROOT"/*.md | sed "s@\(${ROOT}/\|\.md:title\)@@g" | sort
}
# }}}

# HELP {{{
function HELP() {
  printf 'Usage: znote [OPTION]\n
  -c, --create
        Create a new note.\n
  -g, --tags
        Sort tags alphabetically.\n
  -o, --open
        Open an existing note.\n
  -t, --title
        Sort titles alphabetically.\n\n'
}
# }}}

case "$1" in
-c | --create)
  CREATE
  ;;
-o | --open)
  cd "$ROOT" || exit 11
  nvim -c ':Telescope live_grep'
  ;;
-g | --tag)
  SORT_TAGS_ALPHABETICALLY
  ;;
-t | --title)
  SORT_TITLES_CHRONOLOGICALLY
  ;;
*)
  HELP
  ;;
esac

exit 0
